# @package _global_
defaults:
  - override /data: evo/oas_full
  - override /scoring: d2
  - _self_

task:
  name: evotuning
  runner: evotuning
  stage_type: evotuning

training:
  learning_rate: 2.0e-5
  warmup_steps: 500
  max_epochs: 1
  max_steps: null
  batch_size: 128
  gradient_accumulation_steps: 4
  save_every_n_steps: 5000
  fp16: true
  resume_checkpoint: null
