model_name: facebook/esm2_t12_35M_UR50D
fasta_path: ${PROJECT_DIR}/datasets/c05_single.fasta
finetune: ${PROJECT_DIR}/checkpoints/REPLACE_WITH_C05_5K_RUN_NAME/best.pt
learning_rate: 4.0e-4
max_steps: 30
batch_size: 4
gradient_accumulation_steps: 16
max_seq_len: 256
mlm_probability: 0.15
freeze_embeddings: true
freeze_first_n_layers: 0
fp16: false
seed: 42
train_dir: ${TRAIN_DIR}
project_dir: ${PROJECT_DIR}
wandb_project: ${WANDB_PROJECT}
scoring_n_samples: 10000
scoring_batch_size: 512
scoring_datasets:
  - name: M22
    path: ${PROJECT_DIR}/datasets/scoring/D2_M22.csv
    enrichment_col: M22_binding_enrichment_adj
  - name: SI06
    path: ${PROJECT_DIR}/datasets/scoring/D2_SI06.csv
    enrichment_col: SI06_binding_enrichment_adj
  - name: exp
    path: ${PROJECT_DIR}/datasets/scoring/D2_exp.csv
    enrichment_col: exp_enrichment_adj
